const API_BASE="https://api.openmetrolinx.com/OpenDataAPI/api/V1";
export async function onRequestGet(context){const url=new URL(context.request.url),mode=(url.searchParams.get("mode")||"delay").trim().toLowerCase(),fromStop=(url.searchParams.get("fromStop")||"WR").trim().toUpperCase(),toStop=(url.searchParams.get("toStop")||"UN").trim().toUpperCase(),startTime=(url.searchParams.get("startTime")||"0700").trim(),tripNumber=(url.searchParams.get("tripNumber")||"").trim(),date=(url.searchParams.get("date")||getTodayYYYYMMDD()).trim();const apiKey=getApiKey(context);if(!apiKey)return jsonResponse({ok:false,error:"GO_API_KEY is missing at runtime. Confirm the secret exists in the same Cloudflare Pages environment as this deployment, then redeploy the site so the Function can read it.",availableBindings:getAvailableBindingNames(context)},500);try{if(mode==="next-service"){const nextService=await findStopNextService({apiKey,stopCode:fromStop});return jsonResponse({ok:true,mode,stopCode:fromStop,endpoint:`Stop/NextService/${fromStop}`,serviceCount:nextService.services.length,services:nextService.services.slice(0,12),raw:nextService.raw,checkedAt:new Date().toISOString()});}if(mode==="stop-details"){const stopDetails=await findStopDetails({apiKey,stopCode:fromStop});return jsonResponse({ok:true,mode,stopCode:fromStop,requestedTripNumber:tripNumber||null,endpoint:`Stop/Details/${fromStop}`,raw:stopDetails.raw,checkedAt:new Date().toISOString()});}if(mode==="schedule-trip"){const scheduleTrip=await findScheduleTrip({apiKey,date,tripNumber:tripNumber||"1960"});return jsonResponse({ok:true,mode,date,tripNumber:tripNumber||"1960",endpoint:`Schedule/Trip/${date}/${tripNumber||"1960"}`,westHarbourStop:findStopByCode(scheduleTrip.raw,fromStop),raw:scheduleTrip.raw,checkedAt:new Date().toISOString()});}const journey=tripNumber?null:await findTargetJourney({apiKey,fromStop,toStop,startTime});const matchedTripNumber=tripNumber||extractTripNumber(journey);const trainStatus=matchedTripNumber?await findTrainStatus({apiKey,tripNumber:matchedTripNumber}):null;return jsonResponse({ok:true,fromStop,toStop,startTime,requestedTripNumber:tripNumber||null,matchedTripNumber:matchedTripNumber||null,journey:journey?simplifyJourney(journey):null,trainStatus,delaySeconds:getDelaySeconds(trainStatus),checkedAt:new Date().toISOString()});}catch(error){return jsonResponse({ok:false,error:error.message||"GO lookup failed."},500);}}
function getApiKey(context){return(context?.env?.GO_API_KEY||context?.env?.METROLINX_API_KEY||globalThis?.GO_API_KEY||"").toString().trim();}
function getAvailableBindingNames(context){return Object.keys(context?.env||{}).sort();}
function getTodayYYYYMMDD(){return new Date().toISOString().slice(0,10).replaceAll("-","");}
async function findStopNextService({apiKey,stopCode}){const raw=await fetchJson(`${API_BASE}/Stop/NextService/${encodeURIComponent(stopCode)}?key=${encodeURIComponent(apiKey)}`);return{raw,services:findArray(raw)};}
async function findStopDetails({apiKey,stopCode}){const raw=await fetchJson(`${API_BASE}/Stop/Details/${encodeURIComponent(stopCode)}?key=${encodeURIComponent(apiKey)}`);return{raw};}
async function findScheduleTrip({apiKey,date,tripNumber}){const raw=await fetchJson(`${API_BASE}/Schedule/Trip/${encodeURIComponent(date)}/${encodeURIComponent(tripNumber)}?key=${encodeURIComponent(apiKey)}`);return{raw};}
async function findTargetJourney({apiKey,fromStop,toStop,startTime}){const data=await fetchJson(`${API_BASE}/Stop/NextService/${encodeURIComponent(fromStop)}/${encodeURIComponent(toStop)}/${encodeURIComponent(startTime)}?key=${encodeURIComponent(apiKey)}`),journeys=findArray(data);if(!journeys.length)return null;return journeys.map(journey=>({journey,score:scoreJourney(journey)})).sort((a,b)=>a.score-b.score)[0].journey;}
async function findTrainStatus({apiKey,tripNumber}){const data=await fetchJson(`${API_BASE}/ServiceataGlance/Trains/All?key=${encodeURIComponent(apiKey)}`),trains=findArray(data),target=normalizeTripId(tripNumber);return trains.find(train=>[train.TripNumber,train.TrainNumber,train.TripID,train.TripId,train.Trip,train.ServiceNumber].map(normalizeTripId).some(candidate=>isTripMatch(candidate,target)))||null;}
async function fetchJson(url){const response=await fetch(url,{headers:{Accept:"application/json"}});if(!response.ok)throw new Error(`GO API returned HTTP ${response.status}`);return response.json();}
function findArray(value){if(Array.isArray(value))return value;if(!value||typeof value!=="object")return[];for(const item of Object.values(value)){if(Array.isArray(item))return item;const nested=findArray(item);if(nested.length)return nested;}return[];}
function findStopByCode(value,code){const arr=findArray(value),target=String(code||"").toLowerCase();return arr.find(item=>JSON.stringify(item).toLowerCase().includes(`"code":"${target}"`)||JSON.stringify(item).toLowerCase().includes(`"stopcode":"${target}"`)||JSON.stringify(item).toLowerCase().includes(`"stationcode":"${target}"`))||null;}
function scoreJourney(journey){const text=JSON.stringify(journey).toLowerCase();let score=100;if(text.includes("7:54")||text.includes("0754")||text.includes("7:53")||text.includes("0753"))score-=50;if(text.includes("union"))score-=10;if(text.includes("west harbour")||text.includes("westharbour"))score-=10;return score;}
function extractTripNumber(journey){if(!journey)return"";const found=findFirstKey(journey,["TripNumber","TrainNumber","TripID","TripId","Trip","ServiceNumber"]);return found?String(found):"";}
function normalizeTripId(value){return String(value||"").trim().toLowerCase();}
function isTripMatch(candidate,target){if(!candidate||!target)return false;if(candidate===target)return true;const candidateParts=candidate.split("-").filter(Boolean),targetParts=target.split("-").filter(Boolean),candidateLast=candidateParts[candidateParts.length-1],targetLast=targetParts[targetParts.length-1];if(candidateLast&&targetLast&&candidateLast===targetLast)return true;if(candidate.endsWith(`-${target}`))return true;if(target.endsWith(`-${candidate}`))return true;return false;}
function findFirstKey(value,keys){if(!value||typeof value!=="object")return null;for(const key of keys){if(Object.prototype.hasOwnProperty.call(value,key)&&value[key])return value[key];}for(const child of Object.values(value)){if(typeof child==="object"){const found=findFirstKey(child,keys);if(found)return found;}}return null;}
function simplifyJourney(journey){const tripNumber=extractTripNumber(journey),text=JSON.stringify(journey);return{possibleTripNumber:tripNumber||null,preview:text.length>1200?`${text.slice(0,1200)}...`:text};}
function getDelaySeconds(trainStatus){if(!trainStatus)return null;const raw=trainStatus.DelaySeconds??trainStatus.delaySeconds??trainStatus.Delay??null,parsed=Number(raw);return Number.isFinite(parsed)?parsed:null;}
function jsonResponse(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});}
